### ISSUE TITLE
豆瓣电影在线观看插件     跳转链接基本都没有了，只有部分国内主流影视软件跳转。

### ISSUE THREAD

**Issue by lordmanth** [anc95/monkey-scripts#1]

**Comment by anc95** [comment]
@lordmanth 我看一下

**Comment by anc95** [comment]
已经修复了 注意更新下脚本就行
<img width="1182" alt="image" src="https://user-images.githubusercontent.com/13167934/194687863-9b3d7328-775f-4f3a-b019-84c9991a8fed.png">

**Comment by lordmanth** [comment]
好的，刚才试了，已经可以使用了，感谢作者大大！！
&nbsp;


虚日度年轮
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年10月8日(星期六) 中午12:22
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [anc95/monkey-scripts] 豆瓣电影在线观看插件     跳转链接基本都没有了，只有部分国内主流影视软件跳转。 (Issue #1)





 
已经修复了 注意更新下脚本就行
